<link href="/modules/addons/TrustOceanSSLAdmin/assets/css/clientarea.css" rel="stylesheet">
<table class="to-ssl-management-table">
    <thead>
        <tr>
            <th>证书ID</th>
            <th>基本信息</th>
            <th>状态</th>
            <th>验证类型</th>
            <th>创建日期</th>
            <th>过期日期</th>
            <th>域名列表</th>
            <th>管理</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
        </tr>
        <tr>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
        </tr>
    <tr>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
        </tr>
    <tr>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
        </tr>
    <tr>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
            <td>23</td>
        </tr>
    </tbody>
</table>